title: Listen for DTMF digits on an Inbound Calls with NeRu
description: Create and deploy a NeRu project that listens for DTMF digits on an inbound call.
products:
  - neru
languages: 
  - javascript

introduction:
  title: Introduction to this tutorial
  description: This tutorial will take you through creating and deploying a NeRu project that listens for DTMF digits on an inbound call and relays it back with text-to-speech.
  content: |
    # Introduction
    [NeRu](/neru/overview) allows you to create and deploy serverless backends for your Vonage Applications.

    This tutorial is will be using the [Voice](/neru/providers/voice) and [State](/neru/providers/state) providers in the NeRu SDK. 

prerequisites:
  - create-nexmo-account
  - install-nodejs
  - install-nexmo-cli
  - install-neru-cli

tasks:
  - neru/create-vonage-application
  - buy-nexmo-number
  - link-nexmo-number
  - neru/create-project
  - neru/create-server
  - neru/listen-inbound-calls
  - neru/inbound-dtmf/inbound-call-route
  - neru/inbound-dtmf/inbound-dtmf-route
  - neru/view-dashboard

conclusion:
  title: What's next?
  description: What else can you do with NeRu?
  content: |

    # What's next?
    
    Try [debugging](/neru/debugging) your project locally, or view the other [NeRu tutorials](/neru/tutorials).
